module.exports = {
    // Auth & User Events
    ACCOUNT_CREATED: 'ACCOUNT_CREATED',
    EMAIL_VERIFIED: 'EMAIL_VERIFIED',
    MPIN_CREATED: 'MPIN_CREATED',

    // Lending Events
    LOAN_CREATED: 'LOAN_CREATED',
    LOAN_RECEIVED: 'LOAN_RECEIVED',
    AGREEMENT_READY: 'AGREEMENT_READY',
    AGREEMENT_ACCEPTED: 'AGREEMENT_ACCEPTED',
    LOAN_ACTIVATED: 'LOAN_ACTIVATED',
    PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    LOAN_COMPLETED: 'LOAN_COMPLETED',
    LOAN_CLOSED: 'LOAN_CLOSED',

    // Future Chit Fund Events
    CHIT_INVITE: 'CHIT_INVITE',
    CHIT_JOINED: 'CHIT_JOINED',
    CHIT_CONTRIBUTION_DUE: 'CHIT_CONTRIBUTION_DUE',
    AUCTION_OPENED: 'AUCTION_OPENED',
    AUCTION_CLOSED: 'AUCTION_CLOSED',
    CHIT_PAYOUT: 'CHIT_PAYOUT'
};
