const PDFDocument = require('pdfkit');
const admin = require('firebase-admin');
const { v4: uuidv4 } = require('uuid');

async function generateAndUploadClosureCertificate(loan) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, size: 'A4' });
            const buffers = [];
            
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', async () => {
                const pdfData = Buffer.concat(buffers);
                
                try {
                    const bucketName = process.env.FIREBASE_STORAGE_BUCKET || 'khatha-firebase.appspot.com'; 
                    // To handle default or custom buckets
                    const bucket = admin.storage().bucket(bucketName);
                    
                    const filename = `certificates/closure_${loan._id}_${uuidv4()}.pdf`;
                    const file = bucket.file(filename);

                    await file.save(pdfData, {
                        metadata: {
                            contentType: 'application/pdf',
                        },
                        public: true
                    });

                    // Construct public URL
                    // Note: modern firebase storage might require signed URLs, but making it public allows read access.
                    await file.makePublic();
                    const publicUrl = `https://storage.googleapis.com/${bucket.name}/${filename}`;
                    
                    resolve(publicUrl);
                } catch (uploadError) {
                    console.error('[PDFGenerator] Storage Upload Failed. Returning generated bytes only.', uploadError.message);
                    // We still return successfully but without a URL if the bucket isn't correctly configured
                    resolve(null);
                }
            });

            // Document Content Formatting
            doc.fontSize(24).font('Helvetica-Bold').text('NO DUES CERTIFICATE', { align: 'center' });
            doc.moveDown();
            doc.fontSize(12).font('Helvetica').text(`Date: ${new Date().toLocaleDateString()}`);
            doc.moveDown(2);
            
            doc.fontSize(14).font('Helvetica-Bold').text('To Whom It May Concern,');
            doc.moveDown();
            
            doc.fontSize(12).font('Helvetica').text(
                `This is to certify that the loan agreement (Reference ID: ${loan._id}) between ` +
                `the Lender and the Borrower (${loan.borrowerName}) has been fully settled.`
            );
            doc.moveDown();
            
            doc.rect(50, doc.y, 500, 150).stroke();
            doc.moveDown(0.5);
            doc.text(`   Principal Amount: Rs. ${loan.amount}`, { indent: 10 });
            doc.moveDown(0.5);
            doc.text(`   Interest Rate: ${loan.interestRate}%`, { indent: 10 });
            doc.moveDown(0.5);
            doc.text(`   Start Date: ${loan.startDate ? new Date(loan.startDate).toLocaleDateString() : 'N/A'}`, { indent: 10 });
            doc.moveDown(0.5);
            doc.text(`   Closing Date: ${new Date().toLocaleDateString()}`, { indent: 10 });
            doc.moveDown(0.5);
            doc.text(`   Final Status: CLOSED & SETTLED`, { indent: 10 });
            
            doc.moveDown(5);
            doc.text('This is a digitally generated document stored immutably on Khatha servers and does not require a physical signature.', { align: 'center', color: 'grey' });
            
            doc.end();
            
        } catch (error) {
            console.error('[PDFGenerator] Error generating PDF:', error);
            reject(error);
        }
    });
}

module.exports = { generateAndUploadClosureCertificate };
