const mongoose = require('mongoose');

/**
 * OtpChallenge — Server-side transactional OTP for payment authorization.
 * 
 * SECURITY PROPERTIES (as specified):
 * - Bound to exact intentId → loanId, lender, borrower, amount
 * - Server-generated 6-digit OTP (NOT Firebase Phone Auth)
 * - Stored as bcrypt hash — never logged, never returned in responses
 * - Single-use: status → CONSUMED on successful verification
 * - Short-lived: 5-minute TTL (Mongo TTL index auto-deletes)
 * - Attempt-limited: max 5 attempts, then LOCKED
 * - Rate-limited at intent level (one active challenge per intent)
 * 
 * IMPORTANT: This is SEPARATE from login OTP. Payment OTP is:
 * - Generated by the server (crypto.randomInt)
 * - Sent via push notification to borrower
 * - Never creates an in-app history entry containing the OTP
 */
const OtpChallengeSchema = new mongoose.Schema({
    intentId: {
        type: String,
        required: true,
        index: true
    },
    otpHash: {
        type: String,
        required: true
    },
    borrowerUserId: {
        type: String,
        required: true
    },
    lenderUserId: {
        type: String,
        required: true
    },
    loanId: {
        type: String,
        required: true
    },
    amountPaise: {
        type: Number,
        required: true
    },
    attemptsRemaining: {
        type: Number,
        default: 5
    },
    status: {
        type: String,
        enum: ['ACTIVE', 'CONSUMED', 'EXPIRED', 'LOCKED'],
        default: 'ACTIVE'
    },
    createdAt: {
        type: Date,
        default: Date.now,
        expires: 300 // TTL: 5 minutes, auto-deleted by MongoDB
    }
});

// Fast lookup: one active challenge per intent
OtpChallengeSchema.index({ intentId: 1, status: 1 });

module.exports = mongoose.model('OtpChallenge', OtpChallengeSchema);
